export const HTTP_STATUS: Record<number, [string, string]> = {
  100: ["Continue", "Carry on sending the request body."],
  101: ["Switching Protocols", "Changing protocol, usually to WebSocket."],
  102: ["Processing", "Received, but no response yet."],
  103: ["Early Hints", "Preload hints sent before the real response."],
  200: ["OK", "It worked."],
  201: ["Created", "The resource was created. Look for a Location header."],
  202: ["Accepted", "Queued for processing, not finished yet."],
  203: ["Non-Authoritative Information", "A proxy changed the response."],
  204: ["No Content", "It worked, and there is deliberately no body."],
  205: ["Reset Content", "Clear the form you just submitted."],
  206: ["Partial Content", "Only the range you asked for."],
  207: ["Multi-Status", "WebDAV: several statuses in the body."],
  208: ["Already Reported", "WebDAV: already listed earlier."],
  226: ["IM Used", "The response is the result of a delta encoding."],
  300: ["Multiple Choices", "Several options; pick one."],
  301: ["Moved Permanently", "Use the new URL from now on."],
  302: ["Found", "Temporarily somewhere else."],
  303: ["See Other", "Fetch the result from another URL with GET."],
  304: ["Not Modified", "Your cached copy is still good."],
  307: ["Temporary Redirect", "Temporary, and keep the same method."],
  308: ["Permanent Redirect", "Permanent, and keep the same method."],
  400: ["Bad Request", "The request itself is malformed — the server could not parse it."],
  401: ["Unauthorized", "You are not authenticated. Really means 'unauthenticated'."],
  402: ["Payment Required", "Reserved for paid resources."],
  403: ["Forbidden", "Authenticated, but not allowed to do this."],
  404: ["Not Found", "No such resource."],
  405: ["Method Not Allowed", "Right URL, wrong verb."],
  406: ["Not Acceptable", "Cannot produce anything matching your Accept header."],
  407: ["Proxy Authentication Required", "Authenticate with the proxy first."],
  408: ["Request Timeout", "You took too long to send the request."],
  409: ["Conflict", "Clashes with the current state, such as a duplicate."],
  410: ["Gone", "It existed once and was deliberately removed."],
  411: ["Length Required", "Add a Content-Length header."],
  412: ["Precondition Failed", "An If- header did not hold."],
  413: ["Payload Too Large", "The body is bigger than the server accepts."],
  414: ["URI Too Long", "The URL is too long — move data into the body."],
  415: ["Unsupported Media Type", "Wrong Content-Type for this endpoint."],
  416: ["Range Not Satisfiable", "The range you asked for does not exist."],
  417: ["Expectation Failed", "The Expect header cannot be met."],
  418: ["I'm a teapot", "A joke from RFC 2324, still widely implemented."],
  421: ["Misdirected Request", "This server cannot answer for that host."],
  422: ["Unprocessable Content", "Parsed fine, but the values are invalid. Validation errors."],
  423: ["Locked", "WebDAV: the resource is locked."],
  424: ["Failed Dependency", "WebDAV: a previous request failed."],
  425: ["Too Early", "The server will not risk replaying this."],
  426: ["Upgrade Required", "Switch protocol to continue."],
  428: ["Precondition Required", "Send the request conditionally."],
  429: ["Too Many Requests", "Rate limited. Check the Retry-After header."],
  431: ["Request Header Fields Too Large", "Your headers are too big."],
  451: ["Unavailable For Legal Reasons", "Blocked for legal reasons."],
  500: ["Internal Server Error", "The server crashed. Nothing you can fix from outside."],
  501: ["Not Implemented", "The server does not support this at all."],
  502: ["Bad Gateway", "A proxy got a broken reply from upstream."],
  503: ["Service Unavailable", "Overloaded or down for maintenance. Usually temporary."],
  504: ["Gateway Timeout", "A proxy waited too long for upstream."],
  505: ["HTTP Version Not Supported", "The HTTP version is not supported."],
  507: ["Insufficient Storage", "WebDAV: out of space."],
  508: ["Loop Detected", "WebDAV: infinite loop."],
  511: ["Network Authentication Required", "Log in to the network, e.g. a captive portal."],
};

export const statusTone = (code: number) => (code < 300 ? "ok" : code < 400 ? "warn" : "error");
